#!/bin/bash

convert -size 1x1 xc:transparent empty.bmp

[ -d tiles/ ] || mkdir tiles
[ -d palettes/ ] || mkdir palettes

(
  cd tiles/
  for n in {0..943}
  do
    file="tile-$n.bmp"
    [ -h "$file" ] && rm "$file"

    if ! [ -f "$file" ]
    then
      echo "Extract $file..."
      ../../gex ../../rings.bin -t "$n" || ln -s ../empty.bmp "$file"
    fi
  done
)

(
  cd palettes/
  for n in {0..31}
  do
    file="palette-$n.bmp"

    if ! [ -f "$file" ]
    then
      echo "Extract $file..."
      ../../gex ../../rings.bin -c "$n" -w16
    fi
  done
)

OPTIONS="-border 0 -tile 16x -geometry +1+1 -extent 30x -gravity northwest -background pink -font FreeMono-Bold -pointsize 9 +set label"

[ -f tiles-all.png ] ||
montage $OPTIONS \
  label:{0x000,+{1..9},+{a..f}} tiles/tile-{0..255}.bmp \
  label:{0x100,+{1..9},+{a..f}} tiles/tile-{256..511}.bmp \
  label:{0x200,+{1..9},+{a..f}} tiles/tile-{512..767}.bmp \
  label:{0x300,+{1..9},+{a..f}} tiles/tile-{768..943}.bmp \
  tiles-all.png

[ -f tiles-battle.png ] ||
montage $OPTIONS \
  label:{0x200,+{1..9},+{a..f}} tiles/tile-{512..559}.bmp \
  label:{0x330,+{1..9},+{a..f}} tiles/tile-{816..927}.bmp \
  tiles-battle.png

[ -f tiles-people.png ] ||
montage $OPTIONS \
  label:{0x120,+{1..9},+{a..f}} tiles/tile-{288..447}.bmp \
  label:{0x1c0,+{1..9},+{a..f}} tiles/tile-{448..463}.bmp \
  label:{0x250,+{1..9},+{a..f}} tiles/tile-{592..815}.bmp \
  label:{0x3a0,+{1..9},+{a..f}} tiles/tile-{928..943}.bmp \
  tiles-people.png

[ -f tiles-terrain.png ] ||
montage $OPTIONS \
  label:{0x000,+{1..9},+{a..f}} tiles/tile-{0..287}.bmp \
  label:{0x1d0,+{1..9},+{a..f}} tiles/tile-{464..511}.bmp \
  label:{0x230,+{1..9},+{a..f}} tiles/tile-{560..589}.bmp \
  tiles-terrain.png


OPTIONS="-border 0 -tile 1x -geometry +1+1 -extent 128x -gravity north -background pink +set label -pointsize 10"

[ -f palettes-all.png ] ||
montage $OPTIONS palettes/palette-{0..31}.bmp palettes-all.png

[ -f palettes-world.png ] ||
montage $OPTIONS \
  label:'Regular palettes:' \
  palettes/palette-10.bmp label:Day \
  palettes/palette-19.bmp label:Night \
  palettes/palette-23.bmp label:Underwater \
  empty.bmp empty.bmp \
  label:'Flash palettes:' \
  palettes/palette-20.bmp label:Blinding \
  palettes/palette-21.bmp label:Frozen \
  palettes/palette-22.bmp label:Fire \
  palettes/palette-24.bmp label:Lightning \
  palettes-world.png
