#!/usr/bin/env ruby
# frozen_string_literal: true

# Rings of Power Graphics Extractor

$LOAD_PATH.unshift("#{File.dirname(__FILE__)}/lib")

require 'layoutable'
require 'bmp_writer'
require_relative 'romlayout'

romfile = ARGV.shift
warn 'No ROM specified' unless romfile
ROM = RingsOfPower.apply_to(File.binread(romfile))

def lzss_load(directory, files, index)
  entry = ROM[directory][index]

  warn "#{directory}[#{index}] is type #{type} - this could go un-well!" unless entry[:type] == 1
  ROM[files][entry[:offset]]
end

while param = ARGV.shift
  if param =~ /^-(\w)(.*)/
    param = $1
    ARGV.unshift $2 unless $2.empty?
  end

  arg = ARGV.shift.to_i if 'pmcgiw'.include? param

  case param
  when 'p' # Extract portrait
    @outname = "portrait-#{arg}"
    file = lzss_load(:portrait_directory, :portrait_files, arg)

    @sega_palette = file.values_at(*(0..15).to_a)
    @pattern_pixels = file[:pixels]
    @cells_wide = 6

  when 'm' # Extract map
    @outname = "map-#{arg}"
    @pattern_pixels = lzss_load(:lzss_directory, :lzss_files, 10)
    @palette_number = 10
    @cells_wide = arg < 77 || arg >= 230 ? 32 : 11

    lookup = ROM[:ingame_map_lookup].load_all
    map_grid = lzss_load(:map_directory, :map_files, arg)
    @pattern_grid = map_grid.map do |t|
      tile = t[0..8]
      version = t[12].zero? ? :normal : :mirror
      entry = lookup[tile][version]
      [entry[2..], entry[0].nonzero?, entry[1].nonzero? ]
    end

  when 'c' # Specify palette colours (raw palette)
    @outname ||= "palette-#{arg}"
    @palette_number = arg
  when 'g' # Specify pattern grid (LZSS resource)
    @outname ||= "grid-#{arg}"
    @pattern_grid = lzss_load(:lzss_directory, :lzss_files, arg).unpack('n*').map do |e|
      [e[0..10], e[11].nonzero?, e[12].nonzero?]
    end
  when 'i' # Specify pattern image pixels
    @outname ||= "patterns-#{arg}"
    @pattern_pixels = lzss_load(:lzss_directory, :lzss_files, arg)
  when 'w' # Specify output width (in cells)
    @cells_wide = arg
  else
    warn "Unknown parameter -#{param}"
    exit 1
  end
end

def convert_palette
  @sega_palette.map do |c|
    rgba = [c[8..11], c[4..7], c[0..3], c[12..15]]
    rgba.map { |ch| ch * 0x12 }
  end
end

def default_palette
  bright = [0x00, 0x66]
  value = [0x00, 0x99]
  Array.new(16) { |n|
    i = bright[n[3]]
    [i + value[n[0]], i + value[n[1]], i + value[n[2]], 0]
  }
end

def calibrate_grid!
  # Default to making a squareish dump image
  length = @pattern_grid.length
  @cells_wide ||= (length ** 0.5).floor

  d, m = length.divmod(@cells_wide)
  @cells_high = m.zero? ? d : d + 1
  @pattern_grid += [nil] * m
end

def restripe_data
  cells = @pattern_grid.each_slice(@cells_wide).to_a
  lines = @pattern_pixels.unpack('V*')
  patterns = lines.each_slice(8).to_a
  reverses = lines.map { |p| format('%08x', p).reverse.to_i(16) }.each_slice(8).to_a

  (8 * @cells_high).times.flat_map do |y|
    row, line = y.divmod(8)
    Array.new(@cells_wide) do |col|
      p, hf, vf = cells[row][col]
      next 0 unless p

      pat = hf ? reverses[p] : patterns[p]
      l = vf ? 7 - line : line

      pat ? pat[l] : 0
    end
  end.pack('V*')
end

def dump_histogram
  histogram = @bmp_data.unpack1('H*').chars.tally
  histogram.sort.each do |k, v|
    i = k.to_i(16)
    warn format('%<index>2d: %<count>d entries', index: i, count: v)
  end

  warn "#{histogram.count} used colours"
  warn "#{histogram.values.sum} pixels"
end

@sega_palette = ROM[:palettes][@palette_number] if @palette_number
rgb0_palette = @sega_palette ? convert_palette : default_palette
warn "Palette: #{rgb0_palette.map { |e| format('%02x%02x%02x', *e) }.join(' ')}"

# No pixels or grid - palette swatch
unless @pattern_pixels || @pattern_grid
  @pattern_pixels = 16.times.flat_map { |n| [n * 0x11111111] * 8 }.pack('V*')
end

@pattern_grid ||= Array.new(@pattern_pixels.length / 32, &:itself)
# @pattern_pixels ||= TODO

warn "Grid size: #{@pattern_grid.length} entries"

calibrate_grid!
warn "Geometry: #{@cells_wide} x #{@cells_high} cells"

@bmp_data = restripe_data
dump_histogram

bmp = BMPWriter.new("#{@outname}.bmp")
bmp.write(@cells_wide * 8, @cells_high * 8, rgb0_palette, @bmp_data)
